spring.application.name=sentinel-aml
# Create this database once in pgAdmin: CREATE DATABASE sentinel_aml;
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_aml
spring.datasource.username=postgres
spring.datasource.password=Swam1368
#${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.flyway.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
server.error.include-message=never
